/**
 * @file dht.c
 * @brief PIO-based DHT11 / DHT22 driver for RP2350 under FreeRTOS.
 */

#include "dht.h"

#include "FreeRTOS.h"
#include "task.h"

#include "pico/time.h"
#include "hardware/pio.h"
#include "dht.pio.h"          /* generated by pico_generate_pio_header() */

/* One frame = 18.6 ms start pulse + ~0.16 ms ACK + 40 bits * ~110 us ~= 23.3 ms. */
#define DHT_FRAME_NOMINAL_MS   24u
#define DHT_FRAME_SLACK_MS     20u

/* ------------------------------------------------------------------------- */

bool dht_init(dht_t *dev, PIO pio, uint sm, uint pin, dht_type_t type)
{
    if (!pio_can_add_program(pio, &dht_program)) {
        return false;
    }

    dev->pio          = pio;
    dev->sm           = sm;
    dev->pin          = pin;
    dev->type         = type;
    dev->last_read_ms = 0;
    dev->primed       = false;
    dev->offset       = pio_add_program(pio, &dht_program);

    dht_program_init(pio, sm, dev->offset, pin);
    return true;
}

/* Rewind the state machine to the top of the program and start it. */
static void dht_arm(dht_t *dev)
{
    pio_sm_set_enabled(dev->pio, dev->sm, false);
    pio_sm_clear_fifos(dev->pio, dev->sm);
    pio_sm_restart(dev->pio, dev->sm);
    pio_sm_clkdiv_restart(dev->pio, dev->sm);
    pio_sm_exec(dev->pio, dev->sm,
                pio_encode_jmp(dev->offset + dht_offset_entry));
    pio_sm_set_enabled(dev->pio, dev->sm, true);
}

static dht_status_t dht_decode(const dht_t *dev, const uint8_t b[5],
                               dht_reading_t *out)
{
    if ((uint8_t)(b[0] + b[1] + b[2] + b[3]) != b[4]) {
        return DHT_ERR_CHECKSUM;
    }

    if (dev->type == DHT_TYPE_DHT11) {
        /* DHT11 sends integer parts; newer parts put tenths in b[1] / b[3]. */
        out->humidity_x10    = (int16_t)(b[0] * 10 + (b[1] % 10));
        out->temperature_x10 = (int16_t)(b[2] * 10 + (b[3] & 0x0F) % 10);

        if (out->humidity_x10 < 0    || out->humidity_x10 > 1000 ||
            out->temperature_x10 < 0 || out->temperature_x10 > 600) {
            return DHT_ERR_RANGE;
        }
    } else {
        out->humidity_x10 = (int16_t)(((uint16_t)b[0] << 8) | b[1]);
        int16_t t = (int16_t)((((uint16_t)b[2] & 0x7Fu) << 8) | b[3]);
        out->temperature_x10 = (b[2] & 0x80u) ? (int16_t)(-t) : t;

        if (out->humidity_x10 < 0     || out->humidity_x10 > 1000 ||
            out->temperature_x10 < -400 || out->temperature_x10 > 800) {
            return DHT_ERR_RANGE;
        }
    }

    for (int i = 0; i < 5; i++) {
        out->raw[i] = b[i];
    }
    return DHT_OK;
}

dht_status_t dht_read(dht_t *dev, dht_reading_t *out)
{
    /* The sensor needs ~1 s of settling after power-up and >= 1 s between
     * conversions. Reading faster returns the previous (stale) sample at best. */
    uint32_t now = to_ms_since_boot(get_absolute_time());
    if (dev->primed && (uint32_t)(now - dev->last_read_ms) < DHT_MIN_INTERVAL_MS) {
        return DHT_ERR_BUSY;
    }
    dev->last_read_ms = now;
    dev->primed       = true;

    dht_arm(dev);

    /* Sleep through the frame rather than spinning: the whole point of pushing
     * the bit timing into PIO is that the CPU stays available to the scheduler. */
    vTaskDelay(pdMS_TO_TICKS(DHT_FRAME_NOMINAL_MS));

    const TickType_t t0      = xTaskGetTickCount();
    const TickType_t timeout = pdMS_TO_TICKS(DHT_FRAME_SLACK_MS);

    while (pio_sm_get_rx_fifo_level(dev->pio, dev->sm) < 5u) {
        if ((TickType_t)(xTaskGetTickCount() - t0) > timeout) {
            pio_sm_set_enabled(dev->pio, dev->sm, false);
            return DHT_ERR_TIMEOUT;
        }
        vTaskDelay(pdMS_TO_TICKS(1));
    }

    uint8_t b[5];
    for (int i = 0; i < 5; i++) {
        b[i] = (uint8_t)(pio_sm_get(dev->pio, dev->sm) & 0xFFu);
    }
    pio_sm_set_enabled(dev->pio, dev->sm, false);   /* line returns to input/idle */

    return dht_decode(dev, b, out);
}

const char *dht_status_str(dht_status_t s)
{
    switch (s) {
        case DHT_OK:           return "ok";
        case DHT_ERR_TIMEOUT:  return "timeout";
        case DHT_ERR_CHECKSUM: return "checksum";
        case DHT_ERR_RANGE:    return "range";
        case DHT_ERR_BUSY:     return "busy";
        default:               return "?";
    }
}
