#pragma once

// Declarations only - no secrets here, safe to commit. The actual byte arrays (including
// the private key) live in aws_credentials.c, which is generated by
// generate_aws_credentials.py from certs/ and is gitignored.
//
// mbedtls requires PEM buffers to include their terminating null byte in the reported
// length - generate_aws_credentials.py takes care of that; don't recreate these arrays
// by hand without preserving it.

extern const unsigned char aws_root_ca_pem[];
extern const unsigned int aws_root_ca_pem_len;

extern const unsigned char aws_device_cert_pem[];
extern const unsigned int aws_device_cert_pem_len;

extern const unsigned char aws_private_key_pem[];
extern const unsigned int aws_private_key_pem_len;
